### ISSUE TITLE
JS Advanced.

### ISSUE THREAD

**Issue by AlekseiIvshin** [zaytsevaleksandrv/training#1]
Task1 - 2 - В промисах лучше возвращать результат, а не вызов функции логирования
Task2 - 2
Task3 - 0 - Интерфейс не по заданию, история хранится вне счетчика
Task4 - 1 - Не вижу дополнительного задания
Task5 - 2 - Лишний clearInterval, страный вызов в строке 156

**Итоговая оценка 0**

**Comment by zaytsevaleksandrv** [comment]
@AlekseiIvshin 
Task3 - 0 - Интерфейс не по заданию, история хранится вне счетчика
Надо было сделать кнопки?

**Comment by AlekseiIvshin** [comment]
Интерфейс имеется в виду внешние методы, с которым мы работаем. По заданию они next & prev, у тебя другие. Да мелочь, НО требования есть требования и им нужно следовать. Например, если один из преподавателей сделает тесты для проверки кода, то твои проходить не будут, тк не соответствуют требуемому.

**Comment by zaytsevaleksandrv** [comment]
@AlekseiIvshin интерфейс в Task3 сделал по заданию

**Comment by AlekseiIvshin** [comment]
Task1 - 2 - В промисах лучше возвращать результат, а не вызов функции логирования
Task2 - 2
Task3 - 1 - Не вижу дополнительного задания
Task4 - 1 - Не вижу дополнительного задания
Task5 - 2 - Лишний clearInterval, страный вызов в строке 156

**Итоговая оценка 1**
