### ISSUE TITLE
Review: JS Advanced. Prototype & OOP

### ISSUE THREAD

**Issue by AlekseiIvshin** [zaytsevaleksandrv/training#2]
Task1 - 1
Task2 - 0
Task3 - 0
Task4 - 0

**Итоговая оценка 0**

**Comment by zaytsevaleksandrv** [comment]
@AlekseiIvshin task 2,3,4 готовы

**Comment by AlekseiIvshin** [comment]
Task1 - 1
Task2 - 1
Task3 - 1
Task4 - 2

**Итоговая оценка 2**
